services:
  monbacprociel:
    container_name: monbacprociel
    build: .
    image: monbacprociel-dev:latest
    ports:
      - "3002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    restart: always