version: '3.8'

services:
  # Ton site statique actuel
  frontend:
    build: .
    ports:
      - "3002:80"
    restart: always

  # Ton nouveau backend de témoignages
  api:
    build: ./api
    ports:
      - "3003:3000"
    volumes:
      - ./api/database:/app/data # Pour ne pas perdre les messages au redémarrage
    restart: always