server {
    listen 80;
    root /usr/share/nginx/html; # On pointe à la racine du dossier html
    index index.html;

    error_page 404 /404.html;

    # Rewrites sans le /public/ devant
    location = /debouches   { rewrite ^ /pages/debouches.html break; }
    location = /formation   { rewrite ^ /pages/formation.html break; }
    location = /projets     { rewrite ^ /pages/projets.html break; }
    location = /stages      { rewrite ^ /pages/stages.html break; }
    location = /temoignages { rewrite ^ /pages/temoignages.html break; }

    location /api/ {
        proxy_pass http://api:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}